version: 2.1
executors:
  worker:
    docker:
      - image: fr3akyphantom/droid-builder:latest
    parallelism: 4
jobs:
  build:
    executor: worker
    steps:
      - run:
          name: SSH
          command: |
            sudo apt update && sudo apt install git aria2 rsync neofetch nano tmux screen xclip silversearch* -y
            wget https://raw.githubusercontent.com/XelXen/Ubuntu-Tmate/master/tmate && sudo apt-get update && sudo apt-get install tmate -y && sudo bash tmate
            wget https://raw.githubusercontent.com/XelXen/Ubuntu-Tmate/master/spam.sh && sh spam.sh
